version: "3.8"

services:
  backend:
    image: auction-flask:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==worker1" # ou outro atributo, se preferir
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==worker2"

  frontend:
    image: auction-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==manager"
    ports:
      - "3000:80"

networks:
  default:
    driver: overlay
